#!/bin/bash -x
# Creation Date 2021.12.16
# Authors: sergio tomasello <sergio@smartme.io>
#          arturo rinaldi <arturo@smartme.io>

# Hex2bin conversion if needed
if [[ "${2##*.}" = "hex" ]]; then
  mv $2 /tmp/sketch.hex
  hex2bin /tmp/sketch.hex
  rm /tmp/sketch.hex
elif [[ "${2##*.}" = "bin" ]]; then
  mv $2 /tmp/sketch.bin
elif [[ "${2##*.}" = "zip" ]]; then
  mv $2 /tmp/sketch.zip
fi

# LOCALES
export LC_ALL=C.UTF-8
export LANG=C.UTF-8

sleep 3

# Arduino 1200 baud trick
stty -F $1 1200
sleep 3

port=${1}

# Espressif32 actual upload
# Reference : https://github.com/platformio/platform-espressif32/blob/feature/arduino-upstream/builder/main.py#L294
echo "upload port is $1"
/usr/bin/esptool --chip "esp32" --port ${port} --baud "921600" \
	--before "default_reset" \
	--after hard_reset write_flash \
	-z --flash_mode "dio" --flash_freq "80m" \
	--flash_size "detect" 0x10000 "/tmp/sketch.bin"

rc=$?

rm /tmp/sketch.bin

exit $rc