#!/bin/bash -x
# Creation Date 2021.12.16
# Authors: sergio tomasello <sergio@smartme.io>
#          arturo rinaldi <arturo@smartme.io>

# Hex2bin conversion if needed
if [[ "${2##*.}" = "hex" ]]; then
  mv $2 /tmp/sketch.hex
  hex2bin /tmp/sketch.hex
  rm /tmp/sketch.hex
elif [[ "${2##*.}" = "bin" ]]; then
  mv $2 /tmp/sketch.bin
fi

sleep 3

# Arduino 1200 baud trick
stty -F $1 1200
sleep 3

port=${1}

# STM32 actual upload
echo "upload port is $1"
arduinoSTM32load -dfu /usr/bin -bin "/tmp/sketch.bin" -port=${port} -v

rc=$?

rm /tmp/sketch.bin

exit $rc